### ISSUE TITLE
Problem Running Dashboard

### ISSUE THREAD

**Issue by jersonjunior** [davidcomfort/dash_sample_dashboard#1]
Firstly congratulations your dashboard is very cool, I am trying to run your dashboard locally but I have the following error when executing it:

```
Running on http://0.0.0.0:8050/cc-travel-report/paid-search/
Debugger PIN: 918-421-685
/usr/local/lib/python3.6/site-packages/dash/resources.py:45: UserWarning:

A local version of https://code.jquery.com/jquery-3.2.1.min.js is not available

/usr/local/lib/python3.6/site-packages/dash/resources.py:45: UserWarning:

A local version of https://codepen.io/bcd/pen/YaXojL.js is not available

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/dash/dash.py", line 581, in index
    pl=plural
dash.exceptions.InvalidIndexException: Missing element new DashRenderer in index.
```

**Comment by jersonjunior** [comment]
solved with pip3.6 install -r requeriments.txt

**Comment by veniciopedrosa** [comment]
@jersonjunior I have same issue with `https://codepen.io/bcd/pen/YaXojL.js` file. I'm using python:3.7.1-slim on Docker.

Your solution is just run pip3.6?

**Comment by jersonjunior** [comment]
Works for me with python.36!

**Comment by veniciopedrosa** [comment]
And solved the YaXojL.js file issue?
